# Generated by Django 4.2.26 on 2025-11-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
