# Generated by Django 4.2.26 on 2025-11-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_profile_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wake_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
