# Generated by Django 4.2.26 on 2025-11-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wake_time',
            field=models.DateTimeField(blank=True, help_text='Optional account-level wake time (stored in user timezone)', null=True),
        ),
    ]
