# Generated by Django 4.2.26 on 2025-11-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_alter_profile_wake_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(default='member', max_length=20),
        ),
    ]
